# Model arguments
model_name_or_path: Qwen/Qwen2.5-3B
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2

# Data training arguments
dataset_name: "~/data/codecontest"
dataset_config: default
dataset_prompt_column: prompt
system_prompt: "You are an AI designed to help solve competitive programming problems by generating Python code."

# GRPO trainer config
bf16: true
beta: 0.01
sync_ref_model: false
ref_model_mixup_alpha: 1
ref_model_sync_steps: 512
use_vllm: true
do_eval: false
gradient_accumulation_steps: 32
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
learning_rate: 1.0e-06
log_completions: true
log_level: info
logging_first_step: true
logging_steps: 1
logging_strategy: steps
lr_scheduler_type: cosine
max_prompt_length: 1024
max_completion_length: 2048
max_steps: 50
num_generations: 14
num_train_epochs: 1
num_iterations: 1
output_dir: data/Qwen2.5-3B-Intuitor-Code
overwrite_output_dir: true
per_device_eval_batch_size: 4
per_device_train_batch_size: 4
push_to_hub: false
report_to:
- wandb
save_strategy: "steps"
save_total_limit: 6
save_steps: 10
seed: 7
warmup_ratio: 0.1